### ISSUE TITLE
Carga de los ejercicios propuestos en la semana tres de Laboratorio iv (Python-JS-Diseño)

### ISSUE THREAD

**Issue by Hiddencelc** [CodeSystem2022/UTENIANOS_cuarto_semestre#24]

**Comment by programacioncarolina1980** [comment]
se carga de manera exitosa trabajo de python y  js semana tres. Y actividades de diseño para desarrolladores

**Comment by programacioncarolina1980** [comment]
se carga lo solicitado en js, java y diseño correspondiente a semana 3
